### ISSUE TITLE
Error during library check

### ISSUE THREAD

**Issue by sebastian-greve** [GreenDelta/lca-collaboration-server-log#10]
Time     Thread     Level     Category     Message
0     JavaFX Application Thread     ERROR     org.openlca.app.navigation.actions.cloud.CommitAction     Error during commit action
org.openlca.cloud.util.WebRequests$WebRequestException: com.sun.jersey.api.client.ClientHandlerException: java.io.IOException: Error writing request body to server
     at org.openlca.cloud.util.WebRequests.call(WebRequests.java:51)
     at org.openlca.cloud.api.LibraryCheckInvocation.execute(LibraryCheckInvocation.java:46)
     at org.openlca.cloud.api.RepositoryClient.lambda$performLibraryCheck$5(RepositoryClient.java:160)
     at org.openlca.cloud.api.RepositoryClient.executeLoggedIn(RepositoryClient.java:376)
     at org.openlca.cloud.api.RepositoryClient.performLibraryCheck(RepositoryClient.java:155)
     at org.openlca.app.navigation.actions.cloud.CommitAction$Runner.checkAgainstLibraries(CommitAction.java:256)
     at org.openlca.app.App.lambda$0(App.java:192)
     at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
    Caused by: com.sun.jersey.api.client.ClientHandlerException: java.io.IOException: Error writing request body to server
     at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:155)
     at com.sun.jersey.api.client.Client.handle(Client.java:652)
     at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
     at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
     at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:560)
     at org.openlca.cloud.util.WebRequests.call(WebRequests.java:60)
     at org.openlca.cloud.util.WebRequests.call(WebRequests.java:42)
     ... 7 more
    Caused by: java.io.IOException: Error writing request body to server
     at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3479)
     at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3462)
     at com.sun.jersey.api.client.CommittingOutputStream.write(CommittingOutputStream.java:90)
     at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
     at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
     at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
     at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
     at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
     at java.io.BufferedWriter.write(BufferedWriter.java:230)
     at java.io.Writer.write(Writer.java:157)
     at com.sun.jersey.core.util.ReaderWriter.writeToAsString(ReaderWriter.java:190)
     at com.sun.jersey.core.provider.AbstractMessageReaderWriterProvider.writeToAsString(AbstractMessageReaderWriterProvider.java:128)
     at com.sun.jersey.core.impl.provider.entity.StringProvider.writeTo(StringProvider.java:88)
     at com.sun.jersey.core.impl.provider.entity.StringProvider.writeTo(StringProvider.java:58)
     at com.sun.jersey.api.client.RequestWriter.writeRequestEntity(RequestWriter.java:300)
     at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:217)
     at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:153)

**Comment by sebastian-greve** [comment]
Features has changed, cant reproduce
