### ISSUE TITLE
Error when initializing database in version 1.2.0

### ISSUE THREAD

**Issue by mangecoeur** [GreenDelta/lca-collaboration-server-log#16]
Trying to install OpenLCA server 1.2.0 using the command:

`sudo /usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar /opt/lca-collaboration-installer-1.2.0_2020-01-21.jar`

Gives the error:

```java
java.sql.SQLIntegrityConstraintViolationException: Column 'ACTIVE_UNTIL'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeUpdate(Unknown Source)
	at com.greendelta.collaboration.installer.Database.init(Database.java:57)
	at com.greendelta.collaboration.installer.Main.main(Main.java:8)
Caused by: ERROR 23502: Column 'ACTIVE_UNTIL'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 6 more
```

It is not possible to log into the server after this.

**Comment by SebastianGreve-GreenDelta** [comment]
This should be fixed with the current 1.3.0 release
